var searchData=
[
  ['getconfiguration',['GetConfiguration',['../class_sem_diff_1_1_core_1_1_repo.html#a73b3696d435d6baa84ac52aabdf4174d',1,'SemDiff::Core::Repo']]],
  ['getcurrentsaved',['GetCurrentSaved',['../class_sem_diff_1_1_core_1_1_repo.html#abc97121e3c0c5a357908f4c1a2936287',1,'SemDiff::Core::Repo']]],
  ['getfilesasync',['GetFilesAsync',['../class_sem_diff_1_1_core_1_1_pull_request.html#a36d9ef337883e21bafa8ffb1e9bd5e39',1,'SemDiff::Core::PullRequest']]],
  ['getpullrequestsasync',['GetPullRequestsAsync',['../class_sem_diff_1_1_core_1_1_repo.html#a77d6e7bcedf22b4cf7f178b2a57ee4b5',1,'SemDiff::Core::Repo']]],
  ['getrepofor',['GetRepoFor',['../class_sem_diff_1_1_core_1_1_repo.html#a4a7eba4f4c9d0422b90793db7c3c7c0f',1,'SemDiff::Core::Repo']]],
  ['githubauthenticationfailureexception',['GitHubAuthenticationFailureException',['../class_sem_diff_1_1_core_1_1_exceptions_1_1_git_hub_authentication_failure_exception.html',1,'SemDiff::Core::Exceptions']]],
  ['githubauthenticationfailureexception',['GitHubAuthenticationFailureException',['../class_sem_diff_1_1_core_1_1_exceptions_1_1_git_hub_authentication_failure_exception.html#a7c0ca2f978bfd21039e91ab553416ba7',1,'SemDiff::Core::Exceptions::GitHubAuthenticationFailureException']]],
  ['githubauthenticationfailureexception_2ecs',['GitHubAuthenticationFailureException.cs',['../_git_hub_authentication_failure_exception_8cs.html',1,'']]],
  ['githubdeserializationexception',['GitHubDeserializationException',['../class_sem_diff_1_1_core_1_1_exceptions_1_1_git_hub_deserialization_exception.html#af6cc484b1ae137b13e8d68c6d0b3bb5f',1,'SemDiff::Core::Exceptions::GitHubDeserializationException']]],
  ['githubdeserializationexception',['GitHubDeserializationException',['../class_sem_diff_1_1_core_1_1_exceptions_1_1_git_hub_deserialization_exception.html',1,'SemDiff::Core::Exceptions']]],
  ['githubdeserializationexception_2ecs',['GitHubDeserializationException.cs',['../_git_hub_deserialization_exception_8cs.html',1,'']]],
  ['githubmessage',['GithubMessage',['../class_sem_diff_1_1_core_1_1_exceptions_1_1_git_hub_authentication_failure_exception.html#a0a90838c5de4562cb7cb347171010d16',1,'SemDiff::Core::Exceptions::GitHubAuthenticationFailureException']]],
  ['githubratelimitexceededexception',['GitHubRateLimitExceededException',['../class_sem_diff_1_1_core_1_1_exceptions_1_1_git_hub_rate_limit_exceeded_exception.html#aa4bbac0a8a612185d90d4d41005e63f0',1,'SemDiff::Core::Exceptions::GitHubRateLimitExceededException']]],
  ['githubratelimitexceededexception',['GitHubRateLimitExceededException',['../class_sem_diff_1_1_core_1_1_exceptions_1_1_git_hub_rate_limit_exceeded_exception.html',1,'SemDiff::Core::Exceptions']]],
  ['githubratelimitexceededexception_2ecs',['GitHubRateLimitExceededException.cs',['../_git_hub_rate_limit_exceeded_exception_8cs.html',1,'']]],
  ['githubunknownerrorexception',['GitHubUnknownErrorException',['../class_sem_diff_1_1_core_1_1_exceptions_1_1_git_hub_unknown_error_exception.html',1,'SemDiff::Core::Exceptions']]],
  ['githubunknownerrorexception_2ecs',['GitHubUnknownErrorException.cs',['../_git_hub_unknown_error_exception_8cs.html',1,'']]],
  ['githuburlnotfoundexception_2ecs',['GitHubUrlNotFoundException.cs',['../_git_hub_url_not_found_exception_8cs.html',1,'']]]
];
